### ISSUE TITLE
PHP requirement

### ISSUE THREAD

**Issue by marcovoliveira** [zendframework/zend-httphandlerrrunner#11]
composer require zendframework/zend-httphandlerrunner

[InvalidArgumentException]                                                   
  Package zendframework/zend-httphandlerrunner at version  has a PHP requirement incompatible with your PHP version (5.6.40)

**Comment by michalbundyra** [comment]
@rezken1 It looks like you are on PHP 5.6, but the package requires PHP 7.1.

**Comment by penraeth** [comment]
And where in your documentation is that requirement specified?

**Comment by snapshotpl** [comment]
https://github.com/zendframework/zend-httphandlerrunner/blob/master/composer.json#L22

**Comment by weierophinney** [comment]
@penraeth Composer raises errors like that when it encounters problems in the current environment that prevent installations. To identify what dependencies are required, you look at the relevant `composer.json`, which @snapshotpl has kindly linked for you in this thread. Dependency requirements are part of a package definition, not the formal documentation, which centers around usage.
