### ISSUE TITLE
composer install fails because http-message-implementaion was not found

### ISSUE THREAD

**Issue by kschroeer** [zendframework/zend-httphandlerrrunner#12]
I'm not be able to include this package in my project (server is PHP 7.2). I execute "composer require zendframework/zend-httphandlerunner" and here's the error output:

    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - Installation request for zendframework/zend-httphandlerrunner ^1.1 -> satisfiable by zendframework/zend-httphandlerrunner[1.1.0].
        - zendframework/zend-httphandlerrunner 1.1.0 requires psr/http-message-implementation ^1.0 -> no matching package found.

**Comment by michalbundyra** [comment]
@kschroeer You need to have in your project some package which implements `psr/http-message-implementation` - https://packagist.org/providers/psr/http-message-implementation

We recommend https://github.com/zendframework/zend-diactoros

So, as you don't have now any, you should run:
```bash
$ composer require zendframework/zend-diactoros zendframework/zend-httphandlerunner
```

**Comment by kschroeer** [comment]
Installing diactoros solved my problem. Thanks!

**Comment by lukewatts** [comment]
These components are so dependent on each other why not just bundle them together?

To get this working you need both Diactoros and Stratigility!

**Comment by weierophinney** [comment]
> These components are so dependent on each other why not just bundle them together?
> 
> To get this working you need both Diactoros and Stratigility!

They don't, though!

You can use **any** PSR-7, PSR-15, or PSR-17 implementation you want; we typehint on those _interfaces_, not specific _implementations_.

Yes, you _can_ use Diactoros and Stratigility to provide them, _but you could use any other implementation as well_. The goal for this particular component is to allow a common way to bootstrap _any_ middleware application. That includes Slim, northwoods/broker, the middlewares/utils dispatcher, etc., as well as any of the PSR-7/PSR-17 libraries, such as guzzle, nyholm/psr-7, etc.

Coupling to Diactoros and/or Stratigility would be directly counter to those goals.
