### ISSUE TITLE
Redundant status code emits?

### ISSUE THREAD

**Issue by mindplay-dk** [zendframework/zend-httphandlerrrunner#14]
I noticed the HTTP status code gets applied with *every* individual `header()` call:

https://github.com/zendframework/zend-httphandlerrunner/blob/master/src/Emitter/SapiEmitterTrait.php#L84-L88

But headers get emitted before the status line:

https://github.com/zendframework/zend-httphandlerrunner/blob/master/src/Emitter/SapiEmitter.php#L28-L29

And the status line gets emitted last, with the status code:

https://github.com/zendframework/zend-httphandlerrunner/blob/master/src/Emitter/SapiEmitterTrait.php#L60-L65

Any reason why it isn't enough to just apply the status code last with `emitStatusLine()`?

Note that this isn't an issue with the code, merely a bit of a comprehension difficulty.

I'm sure it isn't harmful to apply the status code repeatedly - but unless it's meaningful, it's probably confusing more than it is helpful to a person reading the code?

**Comment by weierophinney** [comment]
It's to fix a subtle PHP issue where it overrides the status code when certain headers are emitted: https://github.com/zendframework/zend-diactoros/pull/273

**Comment by mindplay-dk** [comment]
Yes, I understand the reason, but [according](https://github.com/zendframework/zend-diactoros/pull/273#issuecomment-336141723) to @lcobucci, merely reversing the two lines fixes it.

My question is, is it really necessary to pass the status-code for every individual header-line?

From the rest of the comments, I expect the answer is no?

If I understand correctly, you're defensively setting the status code in both places, in case somebody were to think it's a good idea to change the call order in the other function someday?

(This isn't meant as a criticism or anything - I am genuinely trying to understand how this works.)

**Comment by lcobucci** [comment]
@mindplay-dk you're correct when you say that only changing the order would address the issue. I opted to go with the same approach as `symfony/http-foundation` does to indeed be more defensive.

I've tried to explain that in the commit messages but reading them now I realise that the explanation could have been better. Sorry about the confusion :sweat_smile:

**Comment by mindplay-dk** [comment]
@lcobucci thanks, no problem :-)

(I personally wouldn't have done it if it wasn't necessary - most likely, I would have chosen to simply fold the status line and header emits into a single method, so that the order *can't* be accidentally changed. In my opinion, doing unnecessary things only raises questions or creates confusion. Just my opinion.)
